version: "3.8"

services:
  #  PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedules_jobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Cache
  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  # API Service
  api-service:
    build:
      context: ./jobs-schedules.api
      dockerfile: Dockerfile
    container_name: api-service
    restart: always
    env_file:
      - jobs-schedules.api/.production.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  # Worker Service (with dynamic scaling)
  worker-service:
    build:
      context: ./workers-service
      dockerfile: Dockerfile
    deploy:
      replicas: 3 # Adjust number of workers dynamically
    restart: always
    env_file:
      - workers-service/.production.env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
